name: flutter_movies_app_clean_architecture
description: "A flutter movies app with clean architecture principles"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter_launcher_icons: "^0.13.1"
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lint: ^2.2.0

# Flutter launcher icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/movies_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/config/
